channels:
  - conda-forge
  - nodefaults

dependencies:
    - python=3.9.12
    - pip>=19.0
    - pip:
        - numpy==1.22.0
        - pandavro 
        # - git+https://github.com/feathr-ai/feathr.git#subdirectory=feathr_project&egg=feathr[notebook] 
        - feathr --install-option="--no-deps"
        - scikit-learn 
        - azure-core
        - ipykernel
        - pyspark
        - azure-cli
        - azureml-dataset-runtime
        - azure-ai-ml
        - mlflow
        - mltable