trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  # azureServiceConnectionId: '{{ azureServiceConnection.Id }}'
  # Web app name
  webAppName: 'aml-feathr'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  # environmentName: 'feathr-env'
  # Environment file path (.yml)
  environmentPath: 'pipeline/conda.yml'
  requirementsPath: 'pipeline/requirements.txt'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Python version: 3.9.12
  pythonVersion: '3.9.12'
  resourceGroup: 'rizofeathr11'
  workspaceName: 'mlw-basicex-prod-202212150056'
  AzDoServiceConnectionName: 'ADOServiceConnection'
  DataPath: path/to/data

stages:

- stage: Feathr
  displayName: Feathr stage
  jobs:

  - job: CreateEnvironment
    pool:
      vmImage: $(vmImageName)
    variables:
      - group: env-variables
    steps:
      # - task: UsePythonVersion@0
      #   inputs:
      #     versionSpec: '$(pythonVersion)'
      #   displayName: 'Use Python $(pythonVersion)'
      - script: conda env create --file conda.yml
        displayName: Create Anaconda environment
  #     python create_environment.py
  # - script: |
  #     echo "HELLO!"
  #     ls -al
  #     conda init bash
  #     conda env create --file $(environmentPath)
  #     conda activate $(environmentName)
  # 
      - script: |
          # pip install -r $(requirementsPath) --use-deprecated=legacy-resolver
          # $(dataPath) = python pipeline/main.py --resource_prefix $(RESOURCE_PREFIX) --resource_group $(RESOURCE_GROUP) --azure_subscription_id $(AZURE_SUBSCRIPTION_ID) --azure_client_id $(AZURE_CLIENT_ID) --azure_tenant_id $(AZURE_TENANT_ID) --azure_client_secret $(AZURE_CLIENT_SECRET) --adls_key $(ADLS_KEY)
        workingDirectory: $(projectRoot)
  
  # - job: RunFeathr
  #   dependsOn: CreateEnvironment
  #   pool:
  #     vmImage: $(vmImageName)
  #   steps:
  #   - script: |
  #       python pipeline/main.py
  #     workingDirectory: $(projectRoot)

- stage: AML
  displayName: 'AML'
  dependsOn: Feathr
  condition: succeeded()
  jobs:
  - job: AMLJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    # Ask Mufy about team access level SP.
    - task: AzureCLI@2
      displayName: 'Azure CLI'
      inputs:
        azureSubscription: '$(AzDoServiceConnectionName)'
        # scriptType: ps
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          #To install the Machine Learning CLI extension
          az extension remove -n azure-cli-ml
          az extension remove -n ml
          echo "Uninstalled old AzureML CLI."
          az extension add -n ml
          echo "Installed new AzureML CLI."
          az ml job create --file pipeline/aml_job.yml --resource-group $(resourceGroup) --workspace-name $(workspaceName)
        
