$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: taxi-fare-training-feathr
experiment_name: taxi-fare-training-feathr
description: Training Pipeline to train a model that predicts taxi fare price, using Feathr as feature store

# <inputs_and_outputs>
inputs:
  input:
    type: uri_file
    path: azureml:taxi-data@latest
  enable_monitoring: 'false'
  table_name: 'taximonitoring'

outputs:
  train_data:
  val_data:
  test_data:
  trained_model:
  evaluation_output:
  model_info_output_path:
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:

  create_feathr_config:
    parser.add_argument("--project_name", type=str, help="Name of Feathr project.")
    parser.add_argument("--resource_prefix", type=str, help="Resource prefix.")
    parser.add_argument("--spark_cluster", type=str, help="Type of Spark cluster.")
    parser.add_argument("--feathr_config_path", type=str, help="Path to resulting feathr config file.")
    name: create_feathr_config
    display_name: create-feathr-config
    code: ../../../data-science/src
    # TODO: Change the variable workaround to something safer.
    command: >-
      python create_feathr_config.py
      --project_name 'feathr_demo'
      --resource_prefix <resource-prefix>
      --spark_cluster 'azure_synapse'
      --feathr_config_path 'feathr_config.yaml'
    environment: azureml:feathr-demo-env@latest

  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: >-
      pip install -r requirements/feathr-requirements.txt --use-deprecated=legacy-resolver &&
      python prep.py
      --resource_prefix <resource-prefix>
      --resource_group <resource-group>
      --azure_client_id <client-id>
      --azure_tenant_id <tenant-id>
      --azure_client_secret <client-secret>
      --azure_subscription_id <subscription-id>
      --adls_key <adls-key>
    environment: azureml:feathr-demo-env@latest
    # inputs:
    #   data: ${{parent.inputs.input}}
    #   enable_monitoring: ${{parent.inputs.enable_monitoring}}
    #   table_name: ${{parent.inputs.table_name}}
    # outputs:
    #   train_data: ${{parent.outputs.train_data}}
    #   val_data: ${{parent.outputs.val_data}}
    #   test_data: ${{parent.outputs.test_data}}

  train_model:
    name: train_model
    display_name: train-model
    code: ../../../data-science/src
    # TODO: Change the variable workaround to something safer.
    command: >-
      pip install -r requirements/train-requirements.txt --use-deprecated=legacy-resolver &&
      python train.py
      --config_path 'aml_config.json'
      --data_path ${{inputs.data}}
      --registered_model_name feathr-aml-demo
      --azure_tenant_id $AZURE_TENANT_ID
      --azure_client_id $AZURE_CLIENT_ID
      --azure_client_secret $AZURE_CLIENT_SECRET
      --adls_key $ADLS_KEY
    environment: azureml:feathr-demo-env@latest
    inputs:
      data: ${{parent.inputs.input}}


  # evaluate_model:
  #   name: evaluate_model
  #   display_name: evaluate-model
  #   code: ../../../data-science/src
  #   command: >-
  #     python evaluate.py
  #     --model_name ${{inputs.model_name}}
  #     --model_input ${{inputs.model_input}}
  #     --test_data ${{inputs.test_data}}
  #     --evaluation_output ${{outputs.evaluation_output}}
  #   environment: azureml:taxi-train-env@latest
  #   inputs:
  #     model_name: "taxi-model"
  #     model_input: ${{parent.jobs.train_model.outputs.model_output}}
  #     test_data: ${{parent.jobs.prep_data.outputs.test_data}}
  #   outputs:
  #     evaluation_output: ${{parent.outputs.evaluation_output}}

  # register_model:
  #   name: register_model
  #   display_name: register-model
  #   code: ../../../data-science/src
  #   command: >-
  #     python register.py
  #     --model_name ${{inputs.model_name}}
  #     --model_path ${{inputs.model_path}}
  #     --evaluation_output ${{inputs.evaluation_output}}
  #     --model_info_output_path ${{outputs.model_info_output_path}}
  #   environment: azureml:taxi-train-env@latest
  #   inputs:
  #     model_name: "taxi-model"
  #     model_path: ${{parent.jobs.train_model.outputs.model_output}}
  #     evaluation_output: ${{parent.jobs.evaluate_model.outputs.evaluation_output}}
  #   outputs:
  #     model_info_output_path: ${{parent.outputs.model_info_output_path}}
# </jobs>